#!/usr/bin/env tsx
/**
 * Walks the `tokens` object and emits CSS custom properties to
 * src/styles/globals.css. Re-run when tokens change.
 *
 *   pnpm --filter @app/ui generate:tokens
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { tokens } from '../src/theme/tokens';

interface FlatVar {
  name: string;
  value: string;
}

function isPrimitive(v: unknown): v is string | number {
  return typeof v === 'string' || typeof v === 'number';
}

function flatten(prefix: string, obj: unknown, out: FlatVar[]): void {
  if (isPrimitive(obj)) {
    out.push({
      name: `--app-${prefix}`,
      value: typeof obj === 'number' ? String(obj) : obj,
    });
    return;
  }
  if (obj && typeof obj === 'object') {
    for (const [key, val] of Object.entries(obj as Record<string, unknown>)) {
      const segment = key.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
      flatten(prefix ? `${prefix}-${segment}` : segment, val, out);
    }
  }
}

function main(): void {
  const flat: FlatVar[] = [];
  flatten('', tokens, flat);

  const css = [
    '/* Auto-generated by packages/ui/scripts/generate-css-vars.ts. Do not edit by hand. */',
    ':root {',
    ...flat.map((v) => `  ${v.name}: ${v.value};`),
    '}',
    '',
    'html, body { margin: 0; padding: 0; font-family: var(--app-typography-font-family); }',
    '',
  ].join('\n');

  const target = resolve(
    import.meta.dirname,
    '..',
    'src',
    'styles',
    'globals.css',
  );
  writeFileSync(target, css, 'utf8');
  console.log(`Wrote ${flat.length} CSS variables to src/styles/globals.css`);
}

main();
